In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('./data/Life_Expectancy_Data.csv')
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,SchooX1ling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   object
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   object
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  SchooX1ling                      2775 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.1+ KB

In [4]:
df.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
SchooX1ling                        163
dtype: int64

In [5]:
df = df.drop('Total expenditure', axis=1)
df = df.drop('percentage expenditure', axis=1)
df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,Hepatitis B,Measles,BMI,under-five deaths,Polio,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,SchooX1ling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,65.0,1154,19.1,83,6.0,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,62.0,492,18.6,86,58.0,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,64.0,430,18.1,89,62.0,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,67.0,2787,17.6,93,67.0,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,68.0,3013,17.2,97,68.0,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,68.0,31,27.1,42,67.0,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,7.0,998,26.7,41,7.0,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,73.0,304,26.3,40,73.0,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,76.0,529,25.9,39,76.0,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,79.0,1483,25.5,39,78.0,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [6]:
df.isna().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
SchooX1ling                        163
dtype: int64

In [7]:
# 나라 찾기
c_countries = df[df['Country'].str.startswith('C', na=False)]['Country'].unique()
print(c_countries)

["Côte d'Ivoire" 'Cabo Verde' 'Cambodia' 'Cameroon' 'Canada'
 'Central African Republic' 'Chad' 'Chile' 'China' 'Colombia' 'Comoros'
 'Congo' 'Cook Islands' 'Costa Rica' 'Croatia' 'Cuba' 'Cyprus' 'Czechia']

In [8]:
df_alcohol = pd.read_csv('./data/alcohol_raw_data.csv')
df_alcohol.head()

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,SA_0000001400,"Alcohol, recorded per capita (15+) consumption...",numeric,EMR,Eastern Mediterranean,Country,AFG,Afghanistan,Year,2022,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2025-06-26T15:00:00.000Z
1,SA_0000001400,"Alcohol, recorded per capita (15+) consumption...",numeric,SEAR,South-East Asia,Country,BGD,Bangladesh,Year,2022,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2025-06-26T15:00:00.000Z
2,SA_0000001400,"Alcohol, recorded per capita (15+) consumption...",numeric,EMR,Eastern Mediterranean,Country,IRN,Iran (Islamic Republic of),Year,2022,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2025-06-26T15:00:00.000Z
3,SA_0000001400,"Alcohol, recorded per capita (15+) consumption...",numeric,EMR,Eastern Mediterranean,Country,KWT,Kuwait,Year,2022,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2025-06-26T15:00:00.000Z
4,SA_0000001400,"Alcohol, recorded per capita (15+) consumption...",numeric,EMR,Eastern Mediterranean,Country,LBY,Libya,Year,2022,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2025-06-26T15:00:00.000Z

In [9]:
df_alcohol.columns.to_list()
# 표 분석
# ParentLocationCode = 지역코드
# ParentLocation = 지역
# SpatialDimValueCode = 국가코드
# Location = 국가
# Period = Year
# FactValueNumeric = 순수 알콜 값(=> pure_alcohol), Value = 소수점 둘째자리에서 반올림
# 수치가 10 이면 알코올을 진짜 10리터 마셨다 -> 4도짜리면 25배, 20도 짜리면 5배 하면 실제값 추측 가능

['IndicatorCode',
 'Indicator',
 'ValueType',
 'ParentLocationCode',
 'ParentLocation',
 'Location type',
 'SpatialDimValueCode',
 'Location',
 'Period type',
 'Period',
 'IsLatestYear',
 'Dim1 type',
 'Dim1',
 'Dim1ValueCode',
 'Dim2 type',
 'Dim2',
 'Dim2ValueCode',
 'Dim3 type',
 'Dim3',
 'Dim3ValueCode',
 'DataSourceDimValueCode',
 'DataSource',
 'FactValueNumericPrefix',
 'FactValueNumeric',
 'FactValueUoM',
 'FactValueNumericLowPrefix',
 'FactValueNumericLow',
 'FactValueNumericHighPrefix',
 'FactValueNumericHigh',
 'Value',
 'FactValueTranslationID',
 'FactComments',
 'Language',
 'DateModified']

In [10]:
# 나라 이름 맞춰주기
df['Country'] = df['Country'].replace({
    "Côte d'Ivoire" : "Cote d'Ivoire" 
})


df_alcohol['Location'] = df_alcohol['Location'].replace({
    "Netherlands (Kingdom of the)": "Netherlands",
    "Türkiye": "Turkey",
    "North Macedonia": "The former Yugoslav republic of Macedonia",
    "Eswatini": "Swaziland"
})

# Merge 실행
df_1 = pd.merge(
    df, 
    df_alcohol[['Location', 'Period', 'ParentLocation', 'SpatialDimValueCode', 'FactValueNumeric']], 
    left_on=['Country', 'Year'], 
    right_on=['Location', 'Period'], 
    how='left'
)

# [4] 컬럼명 정리 및 중복 제거
df_1 = df_1.rename(columns={
    'ParentLocation': 'Region',
    'SpatialDimValueCode': 'Iso_code',
    'FactValueNumeric': 'Alcohol_Consumption'
}).drop(columns=['Location', 'Period'])

In [11]:
df_1.isna().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
SchooX1ling                        163
Region                              37
Iso_code                            37
Alcohol_Consumption                 39
dtype: int64

In [12]:
cols = df_1.columns.to_list()
cols.remove('Region')
cols.remove('Iso_code')
cols.insert(0, 'Region')
cols.insert(1, 'Iso_code')
df_1 = df_1[cols]
df_1 = df_1.drop('Alcohol', axis=1)

In [13]:
df_1 = df_1.drop('Population', axis=1)

In [14]:
df_1 = df_1.drop('Income composition of resources', axis=1)

In [15]:
df_1.isna().sum()

Region                    37
Iso_code                  37
Country                    0
Year                       0
Status                     0
Life expectancy           10
Adult Mortality           10
infant deaths              0
Hepatitis B              553
Measles                    0
 BMI                      34
under-five deaths          0
Polio                     19
Diphtheria                19
 HIV/AIDS                  0
GDP                      448
 thinness  1-19 years     34
 thinness 5-9 years       34
SchooX1ling              163
Alcohol_Consumption       39
dtype: int64

In [16]:
# 나라 찾기 -> csv가 유럽문자 때문에 안불러와져서 따로 확인해봄 (코트디부아르, 튀르키예)
t_countries = df_1[df_1['Country'].str.startswith('T', na=False)]['Country'].unique()
print(t_countries)

['Tajikistan' 'Thailand' 'The former Yugoslav republic of Macedonia'
 'Timor-Leste' 'Togo' 'Tonga' 'Trinidad and Tobago' 'Tunisia' 'Turkey'
 'Turkmenistan' 'Tuvalu']

In [17]:
# schooling data 가져오기
df_schooling = pd.read_csv('./data/mean_year_schooling.csv')
df_schooling.head()

,iso3,country,hdicode,region,hdi_rank_2023,hdi_1990,hdi_1991,hdi_1992,hdi_1993,hdi_1994,...,pop_total_2014,pop_total_2015,pop_total_2016,pop_total_2017,pop_total_2018,pop_total_2019,pop_total_2020,pop_total_2021,pop_total_2022,pop_total_2023
0,AFG,Afghanistan,Low,SA,181.0,0.285,0.291,0.301,0.311,0.305,...,32.792523,33.831764,34.700612,35.688935,36.743039,37.856121,39.068979,40.000412,40.578842,41.454761
1,ALB,Albania,Very High,ECA,71.0,0.654,0.638,0.622,0.624,0.629,...,2.903749,2.898632,2.897867,2.898242,2.894231,2.885009,2.871954,2.849636,2.827608,2.811655
2,DZA,Algeria,High,AS,96.0,0.595,0.596,0.601,0.603,0.603,...,39.205030,40.019529,40.850721,41.689299,42.505035,43.294546,44.042091,44.761099,45.477390,46.164219
3,AND,Andorra,Very High,NaN,32.0,NaN,NaN,NaN,NaN,NaN,...,0.073737,0.072174,0.072181,0.073762,0.075162,0.076473,0.077380,0.078364,0.079705,0.080856
4,AGO,Angola,Medium,SSA,148.0,NaN,NaN,NaN,NaN,NaN,...,27.160770,28.157798,29.183070,30.234839,31.297155,32.375633,33.451132,34.532429,35.635029,36.749906

In [18]:
# 데이터 분석
# mys_연도 -> 연도별 데이터
# 데이터 구조가 조금 이상한데...

In [19]:
mys_columns_df = df_schooling.filter(regex='^mys')
mys_columns_df["Iso_code"] = df_schooling["iso3"]
cols = mys_columns_df.columns.to_list()
cols = cols[:34]
cols.insert(0, "Iso_code")
mys_columns_df = mys_columns_df[cols]
mys_columns_df

C:\Users\kwonm\AppData\Local\Temp\ipykernel_14892\2723745763.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mys_columns_df["Iso_code"] = df_schooling["iso3"]

,Iso_code,mys_1990,mys_1991,mys_1992,mys_1993,mys_1994,mys_1995,mys_1996,mys_1997,mys_1998,...,mys_2014,mys_2015,mys_2016,mys_2017,mys_2018,mys_2019,mys_2020,mys_2021,mys_2022,mys_2023
0,AFG,0.871962,0.915267,0.958573,1.001878,1.045184,1.088489,1.123602,1.158715,1.193827,...,2.077493,2.124310,2.268592,2.412873,2.557155,2.701437,2.845718,2.990000,2.514790,2.514790
1,ALB,7.351565,7.349687,7.347809,7.345931,7.344053,7.342176,7.623845,7.905514,8.187183,...,10.008680,9.998020,9.987360,9.976700,10.024848,10.072996,10.121144,10.175311,10.175311,10.175311
2,DZA,3.917092,4.100199,4.283306,4.466413,4.649519,4.832626,4.987919,5.143212,5.298505,...,6.120101,6.300135,6.480169,6.660202,6.840236,7.020270,7.215611,7.416387,7.416387,7.416387
3,AND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.650000,10.570000,10.560000,10.735000,10.910000,11.085000,11.260000,11.435000,11.610000,11.610000
4,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.990000,5.315630,5.417391,5.521100,5.626794,5.734512,5.844292,5.956173,5.956173,5.956173
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,ZZG.ECA,7.385331,7.503647,7.619038,7.728272,7.833083,8.202271,8.306483,8.409549,8.513212,...,10.157157,10.216994,10.317145,10.380280,10.454874,10.540600,10.616870,10.698945,10.700746,10.696732
202,ZZH.LAC,5.521199,5.626629,5.732489,5.838855,5.945792,6.052913,6.167077,6.281840,6.396210,...,8.290509,8.385492,8.553482,8.655926,8.768965,8.884018,8.999194,9.131812,9.131163,9.129518
203,ZZI.SA,2.988092,3.099395,3.209820,3.316542,3.423372,3.533626,3.691510,3.849706,4.008268,...,5.756576,5.899239,5.987034,6.175210,6.327778,6.356844,6.550280,6.547464,6.568632,6.793586
204,ZZJ.SSA,3.342058,3.498218,3.648648,3.808188,3.961974,4.099848,4.157946,4.221364,4.294480,...,5.392516,5.554667,5.661327,5.688085,5.789452,5.948869,5.944340,6.140268,6.175707,6.163414
205,ZZK.WORLD,5.854449,5.974218,6.094155,6.212804,6.331633,6.461763,6.585572,6.708567,6.831545,...,8.141188,8.230140,8.307358,8.401410,8.491572,8.568756,8.658052,8.720694,8.736345,8.775209

In [20]:
df_mys = mys_columns_df.melt(
    id_vars=["Iso_code"],
    value_vars=mys_columns_df.filter(like='mys').columns,
    var_name="Year",
    value_name = "Schooling"
)

df_mys['Year'] = df_mys['Year'].str.replace('mys_','').astype(int)
df_mys

       Iso_code  Year  Schooling
0           AFG  1990   0.871962
1           ALB  1990   7.351565
2           DZA  1990   3.917092
3           AND  1990        NaN
4           AGO  1990        NaN
...         ...   ...        ...
6999    ZZG.ECA  2023  10.696732
7000    ZZH.LAC  2023   9.129518
7001     ZZI.SA  2023   6.793586
7002    ZZJ.SSA  2023   6.163414
7003  ZZK.WORLD  2023   8.775209

[7004 rows x 3 columns]

In [21]:
# 데이터 구해왔으니 합치기

df_2 = pd.merge(
    df_1, 
    df_mys,
    on=['Iso_code', 'Year'], 
    how='left'
)

df_2

,Region,Iso_code,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Hepatitis B,Measles,...,under-five deaths,Polio,Diphtheria,HIV/AIDS,GDP,thinness 1-19 years,thinness 5-9 years,SchooX1ling,Alcohol_Consumption,Schooling
0,Eastern Mediterranean,AFG,Afghanistan,2015,Developing,65.0,263.0,62,65.0,1154,...,83,6.0,65.0,0.1,584.259210,17.2,17.3,10.1,0.00,2.124310
1,Eastern Mediterranean,AFG,Afghanistan,2014,Developing,59.9,271.0,64,62.0,492,...,86,58.0,62.0,0.1,612.696514,17.5,17.5,10.0,0.00,2.077493
2,Eastern Mediterranean,AFG,Afghanistan,2013,Developing,59.9,268.0,66,64.0,430,...,89,62.0,64.0,0.1,631.744976,17.7,17.7,9.9,0.00,2.030677
3,Eastern Mediterranean,AFG,Afghanistan,2012,Developing,59.5,272.0,69,67.0,2787,...,93,67.0,67.0,0.1,669.959000,17.9,18.0,9.8,0.00,1.983860
4,Eastern Mediterranean,AFG,Afghanistan,2011,Developing,59.2,275.0,71,68.0,3013,...,97,68.0,68.0,0.1,63.537231,18.2,18.2,9.5,0.00,1.937043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Africa,ZWE,Zimbabwe,2004,Developing,44.3,723.0,27,68.0,31,...,42,67.0,65.0,33.6,454.366654,9.4,9.4,9.2,5.22,7.054000
2934,Africa,ZWE,Zimbabwe,2003,Developing,44.5,715.0,26,7.0,998,...,41,7.0,68.0,36.7,453.351155,9.8,9.9,9.5,4.96,6.952000
2935,Africa,ZWE,Zimbabwe,2002,Developing,44.8,73.0,25,73.0,304,...,40,73.0,71.0,39.8,57.348340,1.2,1.3,10.0,5.24,6.850000
2936,Africa,ZWE,Zimbabwe,2001,Developing,45.3,686.0,25,76.0,529,...,39,76.0,75.0,42.1,548.587312,1.6,1.7,9.8,4.82,6.697000
2937,Africa,ZWE,Zimbabwe,2000,Developing,46.0,665.0,24,79.0,1483,...,39,78.0,78.0,43.5,547.358878,11.0,11.2,9.8,4.75,6.544000

In [22]:
df_2 = df_2.drop("SchooX1ling", axis=1)
df_2.isna().sum()

Region                    37
Iso_code                  37
Country                    0
Year                       0
Status                     0
Life expectancy           10
Adult Mortality           10
infant deaths              0
Hepatitis B              553
Measles                    0
 BMI                      34
under-five deaths          0
Polio                     19
Diphtheria                19
 HIV/AIDS                  0
GDP                      448
 thinness  1-19 years     34
 thinness 5-9 years       34
Alcohol_Consumption       39
Schooling                114
dtype: int64

In [26]:
# 국가별로 schooling 칼럼의 결측치 개수 확인
missing_pattern = df_2.groupby('Iso_code')['Schooling'].apply(lambda x: x.isnull().sum())

# 결측치가 1개라도 있는 나라만 출력
print(missing_pattern[missing_pattern > 0])

Iso_code
BFA     5
BTN    10
ERI     5
GNB     5
GRD     2
LBN     5
MNE     3
NIU     1
PRK    16
SOM    16
SUR     4
VUT     5
Name: Schooling, dtype: int64

In [30]:
df_2 = df_2.sort_values(['Iso_code', 'Year'])
df_2['Schooling'] = df_2.groupby('Iso_code')['Schooling'].transform(lambda x: x.interpolate(method='linear'))
df_3 = df_2.dropna(subset=['Schooling'])

In [33]:
df_3["Schooling"].count()

np.int64(2824)