In [1104]:
import pandas as pd
import numpy as np

In [1105]:
df = pd.read_csv('../../data/raw/Life Expectancy Data.csv')
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [1106]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

# 정보 확인
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Dtype
---  ------                           -----
 0   Country                          object
 1   Year                             int64
 2   Status                           object
 3   Life expectancy                  float64
 4   Adult Mortality                  float64
 5   infant deaths                    int64
 6   Alcohol                          float64
 7   percentage expenditure           float64
 8   Hepatitis B                      float64
 9   Measles                          int64
 10   BMI                             float64
 11  under-five deaths                int64
 12  Polio                            float64
 13  Total expenditure                float64
 14  Diphtheria                       float64
 15   HIV/AIDS                        float64
 16  GDP                              float64
 17  Population                       float64
 18   thinness  1-19 years            float64
 19   thinness 5-9 years              float64
 20  Income composition of resources  float64
 21  Schooling                        float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.1+ KB
None

In [1107]:
# 컬럼명 앞뒤 공백 제거
df.columns = df.columns.str.strip()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Dtype
---  ------                           -----
 0   Country                          object
 1   Year                             int64
 2   Status                           object
 3   Life expectancy                  float64
 4   Adult Mortality                  float64
 5   infant deaths                    int64
 6   Alcohol                          float64
 7   percentage expenditure           float64
 8   Hepatitis B                      float64
 9   Measles                          int64
 10  BMI                              float64
 11  under-five deaths                int64
 12  Polio                            float64
 13  Total expenditure                float64
 14  Diphtheria                       float64
 15  HIV/AIDS                         float64
 16  GDP                              float64
 17  Population                       float64
 18  thinness  1-19 years             float64
 19  thinness 5-9 years               float64
 20  Income composition of resources  float64
 21  Schooling                        float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.1+ KB

In [1108]:
print("결측치 개수:\n", df.isnull().sum())

결측치 개수:
 Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
BMI                                 34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
HIV/AIDS                             0
GDP                                448
Population                         652
thinness  1-19 years                34
thinness 5-9 years                  34
Income composition of resources    167
Schooling                          163
dtype: int64

In [1109]:
# 필요없는 값 제거
df = df.drop(['percentage expenditure', 'Total expenditure', 'Population', 'Income composition of resources'], axis=1)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 18 columns):
 #   Column                Dtype
---  ------                -----
 0   Country               object
 1   Year                  int64
 2   Status                object
 3   Life expectancy       float64
 4   Adult Mortality       float64
 5   infant deaths         int64
 6   Alcohol               float64
 7   Hepatitis B           float64
 8   Measles               int64
 9   BMI                   float64
 10  under-five deaths     int64
 11  Polio                 float64
 12  Diphtheria            float64
 13  HIV/AIDS              float64
 14  GDP                   float64
 15  thinness  1-19 years  float64
 16  thinness 5-9 years    float64
 17  Schooling             float64
dtypes: float64(12), int64(4), object(2)
memory usage: 413.3+ KB

# 한 나라의 모든 연도에서 column 4개 이상 비어있는 경우 제거

In [1110]:
# 한 나라의 모든 연도가 비어있는 column이 4개 이상일 때
def check_empty_columns(group):
    # 특정 국가에서 모든 값이 NaN인 컬럼의 개수 계산
    empty_col_count = (group.isnull().sum() == len(group)).sum()
    return empty_col_count < 4

df = df.groupby('Country').filter(check_empty_columns)

print("결측치 개수:\n", df.isnull().sum())

결측치 개수:
 Country                   0
Year                      0
Status                    0
Life expectancy           6
Adult Mortality           6
infant deaths             0
Alcohol                 178
Hepatitis B             538
Measles                   0
BMI                      16
under-five deaths         0
Polio                     8
Diphtheria                8
HIV/AIDS                  0
GDP                     436
thinness  1-19 years     16
thinness 5-9 years       16
Schooling               160
dtype: int64

In [1111]:
df.shape

(2918, 18)

# BMI가 없는 나라 제거

In [1112]:
df = df.groupby('Country').filter(lambda x: not x['BMI'].isnull().all())

# GDP 결측치 보강

In [1113]:
gdp_df = pd.read_csv('../../data/raw/GDP.csv', skiprows=4)

gdp_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6767.559229,8244.045660,10056.261393,11507.217151,12187.536361,13233.990517,13892.605143,14700.959808,16055.287787,16548.717387,16620.954556,17750.009564,18828.087059,19216.197235,20681.023027,20740.132583,21307.248251,21949.485996,23700.631990,24171.837133,24845.658484,26736.308944,28171.909401,25134.771230,24093.140151,25712.384302,25119.665545,25813.571441,26129.839062,27458.220154,27441.550214,28440.041688,30082.158423,30645.890602,22759.807175,26749.329609,30975.998912,35718.753119,39498.594129,NaN
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.089204,186.909053,197.367547,225.400079,208.962717,226.836135,240.911794,243.773593,257.143823,281.578894,276.732924,294.814162,311.465053,389.729024,463.468775,479.078798,468.774522,518.358685,571.617317,634.448116,773.301205,777.627960,725.547511,732.345461,650.346841,554.221296,578.317452,664.791813,704.142066,728.243319,822.402999,864.174086,732.910915,709.323534,700.772126,766.522931,746.787335,767.399412,697.079415,670.424213,706.727261,625.827815,630.512328,815.432296,989.015464,1126.297323,1235.266608,1381.552597,1447.545754,1408.753467,1628.905248,1761.989261,1732.038021,1706.022744,1690.166792,1498.875240,1334.470500,1528.104224,1552.073722,1507.085600,1351.591669,1562.416175,1679.327622,1571.449189,1615.396356,NaN
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174.930991,138.706822,178.954088,198.871116,221.763654,254.184249,274.218554,376.223152,381.733238,452.053705,560.621505,606.694676,651.417134,637.087099,625.054942,565.569730,522.082216,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,NaN,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.936832,127.451040,133.823783,139.004980,148.545883,155.561897,162.107340,144.940804,146.186183,161.917968,218.672141,195.859987,230.068904,280.643967,368.294725,413.366170,480.447260,490.839577,523.781318,624.870707,763.011988,1328.793688,1164.188488,873.979407,738.545691,754.905547,582.885076,583.317520,563.117147,512.477735,593.024667,607.840414,567.153365,574.472939,580.008123,866.731606,1069.590240,1091.831529,1141.486651,523.797280,518.969226,532.972787,619.337335,697.481256,838.213392,999.770023,1234.641856,1405.880188,1666.520483,1453.495284,1662.633658,1844.054367,1941.118243,2131.606091,2221.350338,1860.727686,1630.039439,1574.230564,1720.140092,2216.385055,2030.861659,2112.794076,2138.473153,1841.855064,1411.337029,NaN
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,729.111965,657.982649,634.221467,636.832811,650.491094,772.468833,697.526602,770.101140,807.439628,907.747893,965.866840,881.919488,668.706017,449.727895,334.973590,404.294818,531.115367,521.702915,429.188127,392.725539,563.733796,533.586202,999.065856,1133.663320,1451.471179,2145.886211,2930.444286,3515.056790,4578.155265,3645.148466,4101.637156,5184.152691,5702.453063,5688.579162,5649.687625,3641.728939,2051.814621,2790.718869,2860.093648,2493.678844,1759.356199,2303.908127,3682.113151,2916.136633,2665.874448,NaN

In [1114]:
gdp_null_info = df[df['GDP'].isnull()].groupby('Country')['Year'].count().reset_index()
gdp_null_info.columns = ['Country', 'Missing_Years_Count']

gdp_null_info

                                                 Country  Missing_Years_Count
0                                                Bahamas                   16
1                       Bolivia (Plurinational State of)                   16
2                                                  Congo                   16
3                                                Czechia                   16
4                                          Côte d'Ivoire                   16
5                  Democratic People's Republic of Korea                   16
6                       Democratic Republic of the Congo                   16
7                                                  Egypt                   16
8                                                Eritrea                    4
9                                                 Gambia                   16
10                            Iran (Islamic Republic of)                   16
11                                                  Iraq                    4
12                                            Kyrgyzstan                   16
13                      Lao People's Democratic Republic                   16
14                                                 Libya                    4
15                      Micronesia (Federated States of)                   16
16                                      Papua New Guinea                    1
17                                     Republic of Korea                   16
18                                   Republic of Moldova                   16
19                                 Saint Kitts and Nevis                    1
20                                           Saint Lucia                   16
21                      Saint Vincent and the Grenadines                   16
22                                 Sao Tome and Principe                    1
23                                              Slovakia                   16
24                                               Somalia                   13
25                                  Syrian Arab Republic                    8
26             The former Yugoslav republic of Macedonia                   16
27  United Kingdom of Great Britain and Northern Ireland                   16
28                           United Republic of Tanzania                   16
29                              United States of America                   16
30                    Venezuela (Bolivarian Republic of)                   16
31                                              Viet Nam                   16
32                                                 Yemen                   16

In [1115]:
null_gdp_countries = df[df['GDP'].isnull()]['Country'].unique()

print(len(null_gdp_countries))
print()
null_gdp_countries

33

array(['Bahamas', 'Bolivia (Plurinational State of)', "Côte d'Ivoire",
       'Congo', 'Czechia', "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Egypt', 'Eritrea', 'Gambia',
       'Iran (Islamic Republic of)', 'Iraq', 'Kyrgyzstan',
       "Lao People's Democratic Republic", 'Libya',
       'Micronesia (Federated States of)', 'Papua New Guinea',
       'Republic of Korea', 'Republic of Moldova',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Sao Tome and Principe',
       'Slovakia', 'Somalia', 'Syrian Arab Republic',
       'The former Yugoslav republic of Macedonia',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Yemen'],
      dtype=object)

In [1116]:
search_results = []

for country in null_gdp_countries:
    # 해당 국가명이 포함된 월드뱅크의 국가명들을 검색 (대소문자 무시)
    match = gdp_df[gdp_df['Country Name'].str.contains(country.split('(')[0].strip(), case=False, na=False)]['Country Name'].unique()
    
    if len(match) > 0:
        search_results.append(f"기대수명 데이터: [{country}] -> 월드뱅크 후보: {list(match)}")
    else:
        search_results.append(f"기대수명 데이터: [{country}] -> 월드뱅크에서 찾을 수 없음")

# 결과 출력
for res in search_results:
    print(res)

기대수명 데이터: [Bahamas] -> 월드뱅크 후보: ['Bahamas, The']
기대수명 데이터: [Bolivia (Plurinational State of)] -> 월드뱅크 후보: ['Bolivia']
기대수명 데이터: [Côte d'Ivoire] -> 월드뱅크에서 찾을 수 없음
기대수명 데이터: [Congo] -> 월드뱅크 후보: ['Congo, Dem. Rep.', 'Congo, Rep.']
기대수명 데이터: [Czechia] -> 월드뱅크 후보: ['Czechia']
기대수명 데이터: [Democratic People's Republic of Korea] -> 월드뱅크에서 찾을 수 없음
기대수명 데이터: [Democratic Republic of the Congo] -> 월드뱅크에서 찾을 수 없음
기대수명 데이터: [Egypt] -> 월드뱅크 후보: ['Egypt, Arab Rep.']
기대수명 데이터: [Eritrea] -> 월드뱅크 후보: ['Eritrea']
기대수명 데이터: [Gambia] -> 월드뱅크 후보: ['Gambia, The']
기대수명 데이터: [Iran (Islamic Republic of)] -> 월드뱅크 후보: ['Iran, Islamic Rep.']
기대수명 데이터: [Iraq] -> 월드뱅크 후보: ['Iraq']
기대수명 데이터: [Kyrgyzstan] -> 월드뱅크에서 찾을 수 없음
기대수명 데이터: [Lao People's Democratic Republic] -> 월드뱅크에서 찾을 수 없음
기대수명 데이터: [Libya] -> 월드뱅크 후보: ['Libya']
기대수명 데이터: [Micronesia (Federated States of)] -> 월드뱅크 후보: ['Micronesia, Fed. Sts.']
기대수명 데이터: [Papua New Guinea] -> 월드뱅크 후보: ['Papua New Guinea']
기대수명 데이터: [Republic of Korea] -> 월드뱅크에서 찾을 수 없음
기대수명 데이터: [Republic of Moldova] -> 월드뱅크에서 찾을 수 없음
기대수명 데이터: [Saint Kitts and Nevis] -> 월드뱅크에서 찾을 수 없음
기대수명 데이터: [Saint Lucia] -> 월드뱅크에서 찾을 수 없음
기대수명 데이터: [Saint Vincent and the Grenadines] -> 월드뱅크에서 찾을 수 없음
기대수명 데이터: [Sao Tome and Principe] -> 월드뱅크 후보: ['Sao Tome and Principe']
기대수명 데이터: [Slovakia] -> 월드뱅크에서 찾을 수 없음
기대수명 데이터: [Somalia] -> 월드뱅크 후보: ['Somalia, Fed. Rep.']
기대수명 데이터: [Syrian Arab Republic] -> 월드뱅크 후보: ['Syrian Arab Republic']
기대수명 데이터: [The former Yugoslav republic of Macedonia] -> 월드뱅크에서 찾을 수 없음
기대수명 데이터: [United Kingdom of Great Britain and Northern Ireland] -> 월드뱅크에서 찾을 수 없음
기대수명 데이터: [United Republic of Tanzania] -> 월드뱅크에서 찾을 수 없음
기대수명 데이터: [United States of America] -> 월드뱅크에서 찾을 수 없음
기대수명 데이터: [Venezuela (Bolivarian Republic of)] -> 월드뱅크 후보: ['Venezuela, RB']
기대수명 데이터: [Viet Nam] -> 월드뱅크 후보: ['Viet Nam']
기대수명 데이터: [Yemen] -> 월드뱅크 후보: ['Yemen, Rep.']

In [ ]:
#  병합을 위한 임시 매핑 사전 (df 이름 : 월드뱅크 이름)
# '찾을 수 없음'으로 나왔던 나라들도 월드뱅크 표준 명칭을 찾아 반영했습니다.
mapping_dict = {
    "Bahamas": "Bahamas, The",
    "Bolivia (Plurinational State of)": "Bolivia",
    "Côte d'Ivoire": "Cote d'Ivoire",
    "Congo": "Congo, Rep.", # 혹은 Congo, Dem. Rep. 확인 필요 (보통 Congo는 Rep.)
    "Democratic People's Republic of Korea": "Korea, Dem. People's Rep.",
    "Democratic Republic of the Congo": "Congo, Dem. Rep.",
    "Egypt": "Egypt, Arab Rep.",
    "Gambia": "Gambia, The",
    "Iran (Islamic Republic of)": "Iran, Islamic Rep.",
    "Kyrgyzstan": "Kyrgyz Republic",
    "Lao People's Democratic Republic": "Lao PDR",
    "Micronesia (Federated States of)": "Micronesia, Fed. Sts.",
    "Republic of Korea": "Korea, Rep.",
    "Republic of Moldova": "Moldova",
    "Saint Kitts and Nevis": "St. Kitts and Nevis",
    "Saint Lucia": "St. Lucia",
    "Saint Vincent and the Grenadines": "St. Vincent and the Grenadines",
    "Slovakia": "Slovak Republic",
    "Somalia": "Somalia, Fed. Rep.",
    "The former Yugoslav republic of Macedonia": "North Macedonia",
    "United Republic of Tanzania": "Tanzania",
    "United States of America": "United States",
    "Venezuela (Bolivarian Republic of)": "Venezuela, RB",
    "Yemen": "Yemen, Rep."
}

In [1118]:
# 2. 월드뱅크 데이터를 세로(Long format)로 변환
# 2000년부터 2015년까지 데이터만 선택
gdp_long = gdp_df.melt(
    id_vars=['Country Name'], 
    value_vars=[str(year) for year in range(2000, 2016)],
    var_name='Year', 
    value_name='GDP_WB'
)

# 연도를 정수형으로 변환
gdp_long['Year'] = gdp_long['Year'].astype(int)

gdp_long.head()

                  Country Name  Year        GDP_WB
0                        Aruba  2000  20681.023027
1  Africa Eastern and Southern  2000    706.727261
2                  Afghanistan  2000    174.930991
3   Africa Western and Central  2000    518.969226
4                       Angola  2000    563.733796

In [ ]:
# df에 임시 컬럼 생성
df['WB_Name'] = df['Country'].replace(mapping_dict)

# 병합 실행
df = pd.merge(
    df, 
    gdp_long, 
    left_on=['WB_Name', 'Year'], 
    right_on=['Country Name', 'Year'], 
    how='left'
)

# 기존 GDP 결측치에 월드뱅크 GDP 채워넣기
df['GDP'] = df['GDP'].fillna(df['GDP_WB'])

# 임시로 썼던 컬럼들 삭제
df = df.drop(columns=['WB_Name', 'Country Name', 'GDP_WB'])

# 그래도 비어있는 나라들
df[df['GDP'].isnull()]['Country'].unique()

array(["Democratic People's Republic of Korea", 'Eritrea',
       'United Kingdom of Great Britain and Northern Ireland'],
      dtype=object)

In [1120]:
# 보강 후에도 여전히 데이터가 전혀 없는 나라 확인 및 제거
# 특정 나라의 gdp가 모두 nan인지 확인
gdp_missing_countries = df.groupby('Country')['GDP'].transform(lambda x: x.isnull().all())
df = df[~gdp_missing_countries]

df[df['GDP'].isnull()]

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,Hepatitis B,Measles,BMI,under-five deaths,Polio,Diphtheria,HIV/AIDS,GDP,thinness 1-19 years,thinness 5-9 years,Schooling
849,Eritrea,2015,Developing,64.7,255.0,5,NaN,95.0,198,18.6,7,95.0,95.0,0.4,NaN,8.4,8.2,5.0
850,Eritrea,2014,Developing,64.4,261.0,5,0.01,94.0,127,18.0,8,94.0,94.0,0.4,NaN,8.5,8.3,5.0
851,Eritrea,2013,Developing,64.0,266.0,6,0.01,94.0,45,17.5,8,94.0,94.0,0.5,NaN,8.6,8.4,5.0
852,Eritrea,2012,Developing,63.6,274.0,6,0.01,94.0,194,17.0,8,94.0,94.0,0.6,NaN,8.7,8.6,5.0

In [1121]:
df[df['Country'] == 'Eritrea']

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,Hepatitis B,Measles,BMI,under-five deaths,Polio,Diphtheria,HIV/AIDS,GDP,thinness 1-19 years,thinness 5-9 years,Schooling
849,Eritrea,2015,Developing,64.7,255.0,5,NaN,95.0,198,18.6,7,95.0,95.0,0.4,NaN,8.4,8.2,5.0
850,Eritrea,2014,Developing,64.4,261.0,5,0.01,94.0,127,18.0,8,94.0,94.0,0.4,NaN,8.5,8.3,5.0
851,Eritrea,2013,Developing,64.0,266.0,6,0.01,94.0,45,17.5,8,94.0,94.0,0.5,NaN,8.6,8.4,5.0
852,Eritrea,2012,Developing,63.6,274.0,6,0.01,94.0,194,17.0,8,94.0,94.0,0.6,NaN,8.7,8.6,5.0
853,Eritrea,2011,Developing,62.9,286.0,6,0.62,96.0,48,16.5,8,96.0,96.0,0.7,582.775532,8.8,8.7,5.0
854,Eritrea,2010,Developing,62.1,298.0,6,0.61,9.0,51,16.0,9,9.0,9.0,0.9,482.149940,8.9,8.8,5.1
855,Eritrea,2009,Developing,61.4,311.0,6,0.63,92.0,82,15.5,9,92.0,92.0,1.0,43.754450,9.0,8.9,5.2
856,Eritrea,2008,Developing,67.0,322.0,6,0.49,94.0,0,15.1,9,94.0,94.0,1.1,326.825642,9.1,9.1,5.2
857,Eritrea,2007,Developing,62.0,329.0,6,1.23,91.0,55,14.7,9,91.0,91.0,1.3,317.329434,9.2,9.2,5.3
858,Eritrea,2006,Developing,59.7,336.0,7,0.97,94.0,128,14.3,9,94.0,94.0,1.4,297.828588,9.3,9.3,5.3
859,Eritrea,2005,Developing,59.4,34.0,7,1.07,96.0,19,13.9,9,96.0,96.0,1.6,276.758960,9.4,9.5,5.4
860,Eritrea,2004,Developing,59.1,342.0,7,0.64,84.0,24,13.6,10,98.0,98.0,1.8,287.422224,9.6,9.6,5.0
861,Eritrea,2003,Developing,58.8,343.0,7,0.56,91.0,376,13.3,10,95.0,93.0,1.9,232.794546,9.7,9.7,4.7
862,Eritrea,2002,Developing,58.5,343.0,7,0.83,86.0,460,13.1,10,92.0,9.0,1.9,21.768798,9.9,9.9,4.4
863,Eritrea,2001,Developing,58.1,345.0,7,0.61,NaN,204,12.8,10,89.0,86.0,2.0,215.139213,1.0,1.0,4.3
864,Eritrea,2000,Developing,45.3,593.0,7,0.83,NaN,789,12.6,10,82.0,81.0,1.9,28.196949,1.2,1.1,3.9

In [1122]:
# Eritrea 걍 지워버릴게요
df = df[df['Country'] != 'Eritrea']
df[df['GDP'].isnull()]

Empty DataFrame
Columns: [Country, Year, Status, Life expectancy, Adult Mortality, infant deaths, Alcohol, Hepatitis B, Measles, BMI, under-five deaths, Polio, Diphtheria, HIV/AIDS, GDP, thinness  1-19 years, thinness 5-9 years, Schooling]
Index: []

In [1123]:
df['Country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia (Plurinational State of)', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', "Côte d'Ivoire", 'Cabo Verde',
       'Cambodia', 'Cameroon', 'Canada', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia',
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Estonia', 'Ethiopia', 'Fiji',
       'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany',
       'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'Iran (Islamic Republic of)',
       'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
       "Lao People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia (Federated States of)', 'Mongolia', 'Montenegro',
       'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Republic of Korea', 'Republic of Moldova',
       'Romania', 'Russian Federation', 'Rwanda', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'Spain', 'Sri Lanka',
       'Suriname', 'Swaziland', 'Sweden', 'Switzerland',
       'Syrian Arab Republic', 'Tajikistan', 'Thailand',
       'The former Yugoslav republic of Macedonia', 'Timor-Leste', 'Togo',
       'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Republic of Tanzania',
       'United States of America', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Yemen',
       'Zambia', 'Zimbabwe'], dtype=object)

# 알코올 결측치

In [1124]:
print("결측치 개수:\n", df.isnull().sum())
print()
print(df[df['Alcohol'].isnull()]['Country'].unique())

결측치 개수:
 Country                   0
Year                      0
Status                    0
Life expectancy           6
Adult Mortality           6
infant deaths             0
Alcohol                 175
Hepatitis B             512
Measles                   0
BMI                       0
under-five deaths         0
Polio                     8
Diphtheria                8
HIV/AIDS                  0
GDP                       0
thinness  1-19 years      0
thinness 5-9 years        0
Schooling               128
dtype: int64

['Algeria' 'Angola' 'Antigua and Barbuda' 'Argentina' 'Armenia'
 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bhutan'
 'Bolivia (Plurinational State of)' 'Bosnia and Herzegovina' 'Botswana'
 'Brazil' 'Brunei Darussalam' 'Bulgaria' 'Burkina Faso' 'Burundi'
 "Côte d'Ivoire" 'Cabo Verde' 'Cambodia' 'Cameroon' 'Canada'
 'Central African Republic' 'Chad' 'Chile' 'China' 'Colombia' 'Comoros'
 'Congo' 'Costa Rica' 'Croatia' 'Cuba' 'Cyprus' 'Czechia'
 'Democratic Republic of the Congo' 'Denmark' 'Djibouti'
 'Dominican Republic' 'Ecuador' 'Egypt' 'El Salvador' 'Equatorial Guinea'
 'Estonia' 'Ethiopia' 'Fiji' 'Finland' 'France' 'Gabon' 'Gambia' 'Georgia'
 'Germany' 'Ghana' 'Greece' 'Grenada' 'Guatemala' 'Guinea' 'Guinea-Bissau'
 'Guyana' 'Haiti' 'Honduras' 'Hungary' 'Iceland' 'India' 'Indonesia'
 'Iran (Islamic Republic of)' 'Iraq' 'Ireland' 'Israel' 'Italy' 'Jamaica'
 'Japan' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati' 'Kuwait' 'Kyrgyzstan'
 "Lao People's Democratic Republic" 'Latvia' 'Lebanon' 'Lesotho' 'Liberia'
 'Libya' 'Lithuania' 'Luxembourg' 'Madagascar' 'Malawi' 'Malaysia'
 'Maldives' 'Mali' 'Malta' 'Mauritania' 'Mauritius' 'Mexico'
 'Micronesia (Federated States of)' 'Mongolia' 'Montenegro' 'Morocco'
 'Mozambique' 'Myanmar' 'Namibia' 'Nepal' 'Netherlands' 'Nicaragua'
 'Niger' 'Nigeria' 'Oman' 'Pakistan' 'Palau' 'Panama' 'Papua New Guinea'
 'Paraguay' 'Peru' 'Philippines' 'Poland' 'Portugal' 'Qatar'
 'Republic of Korea' 'Republic of Moldova' 'Romania' 'Russian Federation'
 'Rwanda' 'Saint Lucia' 'Saint Vincent and the Grenadines' 'Samoa'
 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia' 'Seychelles'
 'Sierra Leone' 'Slovakia' 'Slovenia' 'Solomon Islands' 'Somalia'
 'South Africa' 'Spain' 'Sri Lanka' 'Suriname' 'Swaziland' 'Sweden'
 'Switzerland' 'Syrian Arab Republic' 'Tajikistan' 'Thailand'
 'The former Yugoslav republic of Macedonia' 'Timor-Leste' 'Togo' 'Tonga'
 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Turkmenistan' 'Uganda'
 'Ukraine' 'United Arab Emirates' 'United Republic of Tanzania'
 'United States of America' 'Uruguay' 'Uzbekistan' 'Vanuatu'
 'Venezuela (Bolivarian Republic of)' 'Viet Nam' 'Yemen' 'Zambia'
 'Zimbabwe']

In [1125]:
alcohol_null_info = df[df['Alcohol'].isnull()].groupby('Country')['Year'].count().reset_index()
alcohol_null_info.columns = ['Country', 'Missing_Years_Count']

alcohol_null_info

                                       Country  Missing_Years_Count
0                                      Algeria                    1
1                                       Angola                    1
2                          Antigua and Barbuda                    1
3                                    Argentina                    1
4                                      Armenia                    1
5                                    Australia                    1
6                                      Austria                    1
7                                   Azerbaijan                    1
8                                      Bahamas                    1
9                                      Bahrain                    1
10                                  Bangladesh                    1
11                                    Barbados                    1
12                                     Belarus                    1
13                                     Belgium                    1
14                                      Belize                    1
15                                       Benin                    1
16                                      Bhutan                    1
17            Bolivia (Plurinational State of)                    1
18                      Bosnia and Herzegovina                    1
19                                    Botswana                    1
20                                      Brazil                    1
21                           Brunei Darussalam                    1
22                                    Bulgaria                    1
23                                Burkina Faso                    1
24                                     Burundi                    1
25                                  Cabo Verde                    1
26                                    Cambodia                    1
27                                    Cameroon                    1
28                                      Canada                    1
29                    Central African Republic                    1
30                                        Chad                    1
31                                       Chile                    1
32                                       China                    1
33                                    Colombia                    1
34                                     Comoros                    1
35                                       Congo                    1
36                                  Costa Rica                    1
37                                     Croatia                    1
38                                        Cuba                    1
39                                      Cyprus                    1
40                                     Czechia                    1
41                               Côte d'Ivoire                    1
42            Democratic Republic of the Congo                    1
43                                     Denmark                    1
44                                    Djibouti                    1
45                          Dominican Republic                    1
46                                     Ecuador                    1
47                                       Egypt                    1
48                                 El Salvador                    1
49                           Equatorial Guinea                    1
50                                     Estonia                    1
51                                    Ethiopia                    1
52                                        Fiji                    1
53                                     Finland                    1
54                                      France                    1
55                                       Gabon                    1
56                                      Gambia                    1
57                                     Georgia                    1
58                                     Germany                    1
59                                       Ghana                    1
60                                      Greece                    1
61                                     Grenada                    1
62                                   Guatemala                    1
63                                      Guinea                    1
64                               Guinea-Bissau                    1
65                                      Guyana                    1
66                                       Haiti                    1
67                                    Honduras                    1
68                                     Hungary                    1
69                                     Iceland                    1
70                                       India                    1
71                                   Indonesia                    1
72                  Iran (Islamic Republic of)                    1
73                                        Iraq                    1
74                                     Ireland                    1
75                                      Israel                    1
76                                       Italy                    1
77                                     Jamaica                    1
78                                       Japan                    1
79                                      Jordan                    1
80                                  Kazakhstan                    1
81                                       Kenya                    1
82                                    Kiribati                    1
83                                      Kuwait                    1
84                                  Kyrgyzstan                    1
85            Lao People's Democratic Republic                    1
86                                      Latvia                    1
87                                     Lebanon                    1
88                                     Lesotho                    1
89                                     Liberia                    1
90                                       Libya                    1
91                                   Lithuania                    1
92                                  Luxembourg                    1
93                                  Madagascar                    1
94                                      Malawi                    1
95                                    Malaysia                    1
96                                    Maldives                    1
97                                        Mali                    1
98                                       Malta                    1
99                                  Mauritania                    1
100                                  Mauritius                    1
101                                     Mexico                    1
102           Micronesia (Federated States of)                    1
103                                   Mongolia                    1
104                                 Montenegro                    2
105                                    Morocco                    1
106                                 Mozambique                    1
107                                    Myanmar                    1
108                                    Namibia                    1
109                                      Nepal                    1
110                                Netherlands                    1
111                                  Nicaragua                    1
112                                      Niger                    1
113                                    Nigeria                    1
114                                       Oman                    1
115                                   Pakistan                    1
116                                      Palau                    1
117                                     Panama                    1
118                           Papua New Guinea                    1
119                                   Paraguay                    1
120                                       Peru                    1
121                                Philippines                    1
122                                     Poland                    1
123                                   Portugal                    1
124                                      Qatar                    1
125                          Republic of Korea                    1
126                        Republic of Moldova                    1
127                                    Romania                    1
128                         Russian Federation                    1
129                                     Rwanda                    1
130                                Saint Lucia                    1
131           Saint Vincent and the Grenadines                    1
132                                      Samoa                    1
133                      Sao Tome and Principe                    1
134                               Saudi Arabia                    1
135                                    Senegal                    1
136                                     Serbia                    1
137                                 Seychelles                    1
138                               Sierra Leone                    1
139                                   Slovakia                    1
140                                   Slovenia                    1
141                            Solomon Islands                    1
142                                    Somalia                    1
143                               South Africa                    1
144                                      Spain                    1
145                                  Sri Lanka                    1
146                                   Suriname                    1
147                                  Swaziland                    1
148                                     Sweden                    1
149                                Switzerland                    1
150                       Syrian Arab Republic                    1
151                                 Tajikistan                    1
152                                   Thailand                    1
153  The former Yugoslav republic of Macedonia                    1
154                                Timor-Leste                    1
155                                       Togo                    1
156                                      Tonga                    1
157                        Trinidad and Tobago                    1
158                                    Tunisia                    1
159                                     Turkey                    1
160                               Turkmenistan                    1
161                                     Uganda                    1
162                                    Ukraine                    1
163                       United Arab Emirates                    1
164                United Republic of Tanzania                    1
165                   United States of America                    1
166                                    Uruguay                    1
167                                 Uzbekistan                    1
168                                    Vanuatu                    1
169         Venezuela (Bolivarian Republic of)                    1
170                                   Viet Nam                    1
171                                      Yemen                    1
172                                     Zambia                    1
173                                   Zimbabwe                    1

In [ ]:
# 몬테 뭐시기 배고 전부 1이라 그냥 나라내에서 평균 내고 싶은데
df.loc[df['Country'] == 'Montenegro', ['Year', 'Alcohol']]

      Year  Alcohol
1730  2015      NaN
1731  2014     0.01
1732  2013     0.01
1733  2012     0.01
1734  2011     6.56
1735  2010     6.56
1736  2009     6.45
1737  2008     6.17
1738  2007     4.98
1739  2006     5.38
1740  2005      NaN
1741  2004     0.01
1742  2003     0.01
1743  2002     0.01
1744  2001     0.01
1745  2000     0.01

In [1127]:
# 일단 alcohol.csv에 잇는지 확인
# 근데 걍 보간하고 싶네
alcohol_df = pd.read_csv('../../data/raw/alcohol.csv')

alcohol_total_df = alcohol_df[alcohol_df['Dim1'] == 'All types'][['Location', 'Period', 'FactValueNumeric']]

alcohol_total_df.head()

                       Location  Period  FactValueNumeric
3                   Afghanistan    2022             0.000
13                   Bangladesh    2022             0.002
81   Iran (Islamic Republic of)    2022             0.000
94                       Kuwait    2022             0.040
105                       Libya    2022             0.000

In [1128]:
alcohol_nulls = df[df['Alcohol'].isnull()][['Country', 'Year']]

alcohol_nulls.head()

                Country  Year
32              Algeria  2015
48               Angola  2015
64  Antigua and Barbuda  2015
80            Argentina  2015
96              Armenia  2015

In [1129]:
check_match = pd.merge(alcohol_nulls, alcohol_total_df, 
                       left_on=['Country', 'Year'], 
                       right_on=['Location', 'Period'], 
                       how='inner')

# csv에서 가져올 수 있는 값들
check_match.head()

               Country  Year             Location  Period  FactValueNumeric
0              Algeria  2015              Algeria    2015              0.47
1               Angola  2015               Angola    2015              6.31
2  Antigua and Barbuda  2015  Antigua and Barbuda    2015              8.89
3            Argentina  2015            Argentina    2015              8.37
4              Armenia  2015              Armenia    2015              4.06

In [1130]:
alcohol_data = alcohol_total_df.copy()
alcohol_data.columns = ['WHO_Country', 'WHO_Year', 'WHO_Value']

df = pd.merge(df, alcohol_data, 
              left_on=['Country', 'Year'], 
              right_on=['WHO_Country', 'WHO_Year'], 
              how='left')

df['Alcohol'] = df['Alcohol'].fillna(df['WHO_Value'])

df = df.drop(columns=['WHO_Country', 'WHO_Year', 'WHO_Value'])

In [1131]:
alcohol_null_info = df[df['Alcohol'].isnull()].groupby('Country')['Year'].count().reset_index()
alcohol_null_info.columns = ['Country', 'Missing_Years_Count']

alcohol_null_info

                                     Country  Missing_Years_Count
0                              Côte d'Ivoire                    1
1                                 Montenegro                    1
2                                Netherlands                    1
3                                      Palau                    1
4                               Saudi Arabia                    1
5                                  Swaziland                    1
6  The former Yugoslav republic of Macedonia                    1
7                                     Turkey                    1

In [ ]:
# who 데이터에서 못 채운 나머지는 보간
df['Alcohol'] = df.groupby('Country')['Alcohol'].transform(lambda x: x.interpolate(limit_direction='both'))

df[df['Alcohol'].isnull()]

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,Hepatitis B,Measles,BMI,under-five deaths,Polio,Diphtheria,HIV/AIDS,GDP,thinness 1-19 years,thinness 5-9 years,Schooling
1923,Palau,2013,Developing,NaN,NaN,0,NaN,99.0,0,83.3,0,99.0,99.0,0.1,1932.12237,0.1,0.1,14.2

In [1133]:
df[df['Country'] == 'Palau']

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,Hepatitis B,Measles,BMI,under-five deaths,Polio,Diphtheria,HIV/AIDS,GDP,thinness 1-19 years,thinness 5-9 years,Schooling
1923,Palau,2013,Developing,NaN,NaN,0,NaN,99.0,0,83.3,0,99.0,99.0,0.1,1932.12237,0.1,0.1,14.2

In [1134]:
# Palau도 연도가 하나 밖에 없어서 걍 지워버릴게요
df = df[df['Country'] != 'Palau']
df[df['Alcohol'].isnull()]

Empty DataFrame
Columns: [Country, Year, Status, Life expectancy, Adult Mortality, infant deaths, Alcohol, Hepatitis B, Measles, BMI, under-five deaths, Polio, Diphtheria, HIV/AIDS, GDP, thinness  1-19 years, thinness 5-9 years, Schooling]
Index: []

##### 중간 점검

In [1135]:
print("결측치 개수:\n", df.isnull().sum())

결측치 개수:
 Country                   0
Year                      0
Status                    0
Life expectancy           5
Adult Mortality           5
infant deaths             0
Alcohol                   0
Hepatitis B             512
Measles                   0
BMI                       0
under-five deaths         0
Polio                     8
Diphtheria                8
HIV/AIDS                  0
GDP                       0
thinness  1-19 years      0
thinness 5-9 years        0
Schooling               128
dtype: int64

# B형 간염

In [1136]:
alcohol_null_info = df[df['Hepatitis B'].isnull()].groupby('Country')['Year'].count().reset_index()
alcohol_null_info.columns = ['Country', 'Missing_Years_Count']

alcohol_null_info

                                      Country  Missing_Years_Count
0                                     Algeria                    4
1                                      Angola                    7
2                         Antigua and Barbuda                    1
3                                   Argentina                    2
4                                   Australia                    1
5                                  Azerbaijan                    2
6                                     Bahamas                    1
7                                  Bangladesh                    3
8                                    Barbados                    1
9                                       Benin                    2
10                     Bosnia and Herzegovina                    4
11                               Burkina Faso                    6
12                                    Burundi                    4
13                                 Cabo Verde                    2
14                                   Cambodia                    6
15                                   Cameroon                    5
16                                     Canada                    3
17                   Central African Republic                    9
18                                       Chad                    8
19                                      Chile                    6
20                                    Comoros                    3
21                                      Congo                    7
22                                    Croatia                    7
23                                    Czechia                    2
24                              Côte d'Ivoire                    1
25           Democratic Republic of the Congo                    7
26                                    Denmark                   16
27                                   Djibouti                    7
28                          Equatorial Guinea                   14
29                                    Estonia                    4
30                                   Ethiopia                    7
31                                    Finland                   16
32                                      Gabon                    5
33                                      Ghana                    2
34                                    Grenada                    1
35                                  Guatemala                    5
36                                     Guinea                    7
37                              Guinea-Bissau                    9
38                                     Guyana                    1
39                                      Haiti                   13
40                                    Hungary                   16
41                                    Iceland                   16
42                                      India                    4
43                                    Ireland                   10
44                                    Jamaica                    3
45                                      Japan                   16
46                                      Kenya                    2
47           Lao People's Democratic Republic                    3
48                                    Lesotho                    3
49                                    Liberia                    8
50                                 Madagascar                    2
51                                     Malawi                    2
52                                       Mali                    3
53                                      Malta                    3
54                                 Mauritania                    5
55                                 Montenegro                    6
56                                 Mozambique                    1
57                                    Myanmar                    3
58                                    Namibia                   10
59                                      Nepal                    3
60                                Netherlands                   11
61                                      Niger                    9
62                                    Nigeria                    5
63                                     Norway                   16
64                                   Pakistan                    3
65                                     Panama                    1
66                                   Paraguay                    3
67                                       Peru                    3
68                         Russian Federation                    1
69                                     Rwanda                    2
70                                Saint Lucia                    2
71           Saint Vincent and the Grenadines                    3
72                      Sao Tome and Principe                    3
73                                    Senegal                    4
74                                     Serbia                    4
75                               Sierra Leone                    7
76                                   Slovenia                   16
77                                    Somalia                   13
78                                  Sri Lanka                    3
79                                   Suriname                    5
80                                     Sweden                   11
81                                Switzerland                   16
82                                 Tajikistan                    2
83  The former Yugoslav republic of Macedonia                    5
84                                Timor-Leste                    8
85                                       Togo                    8
86                        Trinidad and Tobago                    2
87                               Turkmenistan                    2
88                                     Uganda                    2
89                United Republic of Tanzania                    2
90                                 Uzbekistan                    2
91                                   Viet Nam                    3
92                                     Zambia                    5

In [1137]:
B_df = pd.read_csv('../../data/raw/Hepatitis_B.csv')
B_df.head()

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,IsLatestYear,Dim1 type,Dim1,Dim1ValueCode,Dim2 type,Dim2,Dim2ValueCode,Dim3 type,Dim3,Dim3ValueCode,DataSourceDimValueCode,DataSource,FactValueNumericPrefix,FactValueNumeric,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,WHS4_117,Hepatitis B (HepB3) immunization coverage among 1-year-olds (%),numeric,EUR,Europe,Country,DNK,Denmark,Year,2024,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,EN,2025-07-13T15:00:00.000Z
1,WHS4_117,Hepatitis B (HepB3) immunization coverage among 1-year-olds (%),numeric,EUR,Europe,Country,FIN,Finland,Year,2024,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,EN,2025-07-13T15:00:00.000Z
2,WHS4_117,Hepatitis B (HepB3) immunization coverage among 1-year-olds (%),numeric,EUR,Europe,Country,HUN,Hungary,Year,2024,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,EN,2025-07-13T15:00:00.000Z
3,WHS4_117,Hepatitis B (HepB3) immunization coverage among 1-year-olds (%),numeric,EUR,Europe,Country,ISL,Iceland,Year,2024,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,EN,2025-07-13T15:00:00.000Z
4,WHS4_117,Hepatitis B (HepB3) immunization coverage among 1-year-olds (%),numeric,EMR,Eastern Mediterranean,Country,SDN,Sudan,Year,2024,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39,NaN,NaN,NaN,NaN,NaN,39,NaN,NaN,EN,2025-07-13T15:00:00.000Z